---
swagger: '2.0'
info:
  title: Lovebot Game Runner
  description: API for registering player AIs and running game simulations of Loveletter
  version: '1.0'
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  "/runGame":
    post:
      x-swagger-router-controller: rungame
      operationId: runGame
      tags:
        - "/runGame"
      description: Specify the players and the parameters of a tournament and get back the results. 
      parameters:
      - name: body
        in: body
        description: The parameters required to run a game
        required: true
        schema:
          type: object
          required:
            - players
          default: |
            {
                "players": [
                    {
                      "name": "Random over HTTP",
                      "aiType": "httpproxy",
                      "strategyUri": "http://localhost:%PLAYERAPIPORT%/api/strategies/0"
                    },
                    {
                      "name": "Good Guesser McGee",
                      "aiType": "goodguess"
                    },
                    {
                      "name": "Drop it",
                      "aiType": "noprincess"
                    }
                ],
                "numberOfMatches": 25,
                "matchesPerGame": 4
            }
          properties:
            players:
              type: array
              items:
                type: object
                required: 
                  - aiType
                  - name
                properties:
                  name:
                    type: string
                    default: 'Player 1'
                  aiType:
                    type: string
                    description: Either a predefined ai type, or httpproxy to specify a remote AI
                    default: httpproxy
                    enum: [random, noprincess, goodguess, httpproxy]
                  strategyUri:
                    type: string
                    description: Only used for remote AIs
                    default: http://localhost:3333/api/strategies/0
            numberOfMatches:
              type: integer
              default: 25
            gamesPerMatch:
              type: integer
              default: 2
      responses:
        '200':
          description: Successful request.
          schema:
            $ref: "#/definitions/GameResult"
        default:
          description: Invalid request
          schema:
            $ref: "#/definitions/Error"
definitions:
  Error:
    properties:
      message:
        type: string
    required:
      - message
  GameResult:
    type: object
    properties:
      gameParameters:
        type: object
        properties:
          numberOfMatches:
            type: integer
            default: 25
          gamesPerMatch:
            type: integer
            default: 4
          totalGames:
            type: integer
            default: 100
      standings:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
              default: Player 1
            place:
              type: integer
              default: 1
            matchesWon:
              type: integer
              default: 20
            matchesWonPct:
              type: number
              default: 0.8